### PR TITLE
Clement jean improvement

### PR DESCRIPTION
**Pull request by coderbyheart**
Closes #2

- [ ] fix timestamp encoding

### CODE REVIEW

**Comment by coderbyheart** [comment]
@Clement-Jean Do you know why the decoded timestamp value becomes `441071100`?

**Comment by coderbyheart** [comment]
https://github.com/coderbyheart/json-protobuf-comparison-wifi-site-survey/actions/runs/3880994478/jobs/6619537328#step:6:93

**Comment by Clement-Jean** [comment]
To be safe I would make the timestamp a `uint64`. This doesn't add overhead. Second, you would have your message:
```js
const message = siteSurvey.create({
  timestamp: BigInt(jsonData.ts).toString(),
  macs: data.map(({ mac }) => BigInt(`0x${mac.replace(/:/g, "")}`).toString()),
  ssids: data.map(({ ssid }) => ssid),
  rssis: data.map(({ rssi }) => rssi),
  channels: data.map(({ chan }) => chan),
})
```

and to print:
```js
console.log({
  ...decoded,
  timestamp: BigInt(decoded.timestamp).toString(),
  macs: decoded.macs.map((mac) => formatMac(parseInt(mac, 10).toString(16))),
});
```

**Comment by coderbyheart** [comment]
Some properties are optional, that's why this approach won't work.

**Pull request closed without merging**
